### ISSUE TITLE
How to run AdaHessianJax in colab?

### ISSUE THREAD

**Issue by dboonz** [nestordemeure/AdaHessianJax#1]
Hi there! Thanks for making this library, I'm excited to try it out!

I was trying to install this in google colab, but it complains that it cannot find AdaHessianJax.jax. [here](https://colab.research.google.com/drive/1BkDBFeR1TnKxV11VqizC9i3pABwkaw29?usp=sharing)'s a link to the notebook: 

```python
!pip install git+https://github.com/nestordemeure/AdaHessianJax.git

import jax
from adahessianJax.jax import adahessian
from adahessianJax import grad_and_hessian
```

Results in:

```
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-8-5da6472b7996> in <module>()
      1 import jax
----> 2 from adahessianJax.jax import adahessian
      3 from adahessianJax import grad_and_hessian

```

How do I properly install it in colab?

**Comment by nestordemeure** [comment]
I can reproduce the problem on Colab but not locally. I will try to fix it within the next 12 hours.

**Comment by dboonz** [comment]
That's great! Thanks a lot!

On March 11, 2021 11:33:37 AM GMT+01:00, Nestor Demeure ***@***.***> wrote:
>I can reproduce the problem, it seems to be mostly a problem of import
>formulation which should be easy to fix. I will try to fix it within
>the next 6 hours.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nestordemeure/AdaHessianJax/issues/1#issuecomment-796637897

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nestordemeure** [comment]
I'm stumped. I have tried relative paths, absolute paths, using `__all__` or not, renaming folders to avoid conflicts and the problem persists.

I can install AdaHessianJax on my machine with no problems but the subfolder parts of the imports fail on Google Collab and I don't know where the difference lies.

**Comment by nestordemeure** [comment]
I finally solved the issue, thank you for putting it to my attention!

I needed to relax the `packages` field in `setup.py`.

(Note that you will need to import from `adahessianJax.jaxOptimizer` instead of `adahessianJax.jax`, I modified it to avoid any conflict between module names)

**Comment by dboonz** [comment]
Great, yes it works, thanks a lot! :)
